/* Class:       MyFriendlyMessage
 * Created On:  
 * Created by:  OpFocus Team
 * Description: 
 */
 
public class MyFriendlyMessage {

	public String msg;
	public String stack_trace;
	public Integer line_number;
	public String ex_type;
	public String first_error;
	public String error_id;
	public Exception orig_ex;
	public String validation_error;
	public String validation_field;
	public String display;
	public String error_object;
	
}